### ISSUE TITLE
kluntje/core README: API description

### ISSUE THREAD

**Issue by samuelecalamita** [kluntje/kluntje#12]
We need a table where the full API is described. The ```<my-amazing-component>``` should show the full API with examples.

**Comment by samuelecalamita** [comment]
@friewerts do we need the [Prerequisites](https://github.com/kluntje/kluntje#prerequisites) section?

**Comment by friewerts** [comment]
no

**Comment by samuelecalamita** [comment]
I think we already updated the docs and this issue can be closed.
