### ISSUE TITLE
export event names

### ISSUE THREAD

**Issue by davidding** [kluntje/kluntje#43]
It would be helpful if event names, e.g.:

* `'kl-in-vp'`
* `'kl-out-vp'`
* `'kl-mq-change'`
* `'kl-component-initialized'`

were importable in our kluntje projects.

**Comment by friewerts** [comment]
how do you mean "importable"? using constants?

**Comment by davidding** [comment]
> how do you mean "importable"? using constants?

That's probably the most straightforward way to do it.

So, in my project I could do something like:

```
import { MQ_CHANGE } from "@kluntje/events";
```

or

```
import { MQ_CHANGE_EVENT } from "@kluntje/core";
```

**Comment by friewerts** [comment]
i would prefer the last one. i think the constants should be part of the related npm module
